aws:
  lambda:
    region: eu-west-1
    accessKeyId: <AWS KEY ID>
    secretAccessKey: <AWS Secret KEY>
    paths:
      resize: <lamda API Path>
  s3:
    region: eu-west-1
    accessKeyId: <AWS KEY ID>
    secretAccessKey: <AWS Secret KEY>
    bucket: <S3 bucket>
  dynamodb:
    region: eu-west-1
    accessKeyId: <AWS KEY ID>
    secretAccessKey: <AWS Secret KEY>
    tables:
      images: images
      tasks: tasks
server:
  port: 3000
logger:
  level: info
